--MbUHmyf6ow7T0hyO

--atv1
SELECT * FROM PRODUTO WHERE STATUS_PRODUTO ILIKE 'ATIVO';

--atv2
SELECT 
	PROD.PRODUTOID,
	CAT.DS_CATEGORIA_PRODUTO,
	PROD.DS_PRODUTO,
	PROD.OBS_PRODUTO,
	PROD.VL_VENDA_PRODUTO,
	PROD.DT_CADASTRO_PRODUTO,
	PROD.STATUS_PRODUTO 
FROM PRODUTO PROD
INNER JOIN CATEGORIA_PRODUTO CAT 
ON PROD.CATEGORIAPRODUTOID = CAT.CATEGORIAPRODUTOID
WHERE PROD.STATUS_PRODUTO ILIKE 'ATIVO';

--atv3
SELECT 
	PROD.PRODUTOID,
	CAT.DS_CATEGORIA_PRODUTO,
	PROD.DS_PRODUTO,
	PROD.OBS_PRODUTO,
	PROD.VL_VENDA_PRODUTO,
	PROD.DT_CADASTRO_PRODUTO,
	PROD.STATUS_PRODUTO 
FROM PRODUTO PROD
INNER JOIN CATEGORIA_PRODUTO CAT 
ON PROD.CATEGORIAPRODUTOID = CAT.CATEGORIAPRODUTOID;
WHERE PROD.VL_VENDA_PRODUTO > 50;

--atv4
SELECT 
	ORC.*,
	CLI.NOME_CLIENTE
FROM ORCAMENTO ORC
INNER JOIN CLIENTE CLI ON ORC.CLIENTEID = CLI.CLIENTEID;

--atv5
SELECT 
	ORCITEM.*,
	PROD.DS_PRODUTO,
	CAT.DS_CATEGORIA_PRODUTO
FROM ORCAMENTO_ITEM ORCITEM
INNER JOIN PRODUTO PROD
ON ORCITEM.PRODUTOID = PROD.PRODUTOID
INNER JOIN CATEGORIA_PRODUTO CAT 
ON PROD.CATEGORIAPRODUTOID = CAT.CATEGORIAPRODUTOID;

--atv6
SELECT * FROM ORCAMENTO WHERE DT_ORCAMENTO BETWEEN '1/2/2026' AND '18/2/2026'

--atv7
SELECT * FROM ORCAMENTO WHERE DT_VALIDADE_ORCAMENTO < CURRENT_DATE;

--atv8
SELECT PRODUTOID, MAX(VL_TOTAL) FROM ORCAMENTO_ITEM GROUP BY PRODUTOID;

--atv9
SELECT ORCAMENTOID, MAX(VL_UNITARIO) FROM ORCAMENTO_ITEM GROUP BY ORCAMENTOID;

--atv10
SELECT SUM(VL_TOTAL_ORCAMENTO) FROM ORCAMENTO

--atv11
SELECT ORCAMENTOID, SUM(QT_PRODUTO) AS TOTAL FROM ORCAMENTO_ITEM GROUP BY ORCAMENTOID;
