INSERT INTO CATEGORIA_PRODUTO (CATEGORIAPRODUTOID, DS_CATEGORIA_PRODUTO) VALUES (1,'BASIC');
INSERT INTO CATEGORIA_PRODUTO (CATEGORIAPRODUTOID, DS_CATEGORIA_PRODUTO) VALUES
(2,'PLATINUM');
INSERT INTO CATEGORIA_PRODUTO (CATEGORIAPRODUTOID, DS_CATEGORIA_PRODUTO) VALUES (3,'PREMIUM');
INSERT INTO CATEGORIA_PRODUTO (CATEGORIAPRODUTOID, DS_CATEGORIA_PRODUTO) VALUES (4,'ELITE');

INSERT INTO CLIENTE (CLIENTEID, TIPO_CLIENTE, CPF_CNPJ_CLIENTE, NOME_CLIENTE) VALUES (1, 'F', '943.051.830-56','JOSÉ DA
SILVA'); 
INSERT INTO CLIENTE (CLIENTEID, TIPO_CLIENTE, CPF_CNPJ_CLIENTE, NOME_CLIENTE) VALUES (2, 'J', '802.202.930-07','PEDRO DE
OLIVEIRA');
INSERT INTO CLIENTE (CLIENTEID, TIPO_CLIENTE, CPF_CNPJ_CLIENTE, NOME_CLIENTE) VALUES (3, 'F', '637.502.500-14','MARIA
EDUARDA MEIRELES');
INSERT INTO CLIENTE (CLIENTEID, TIPO_CLIENTE, CPF_CNPJ_CLIENTE, NOME_CLIENTE) VALUES (4, 'J', '997.192.890-66','SANDRA
GOMES');

INSERT INTO PRODUTO (PRODUTOID, CATEGORIAPRODUTOID , DS_PRODUTO, OBS_PRODUTO,
VL_VENDA_PRODUTO, DT_CADASTRO_PRODUTO, STATUS_PRODUTO) VALUES (1, 1, 'CHAPA
METALICA', 'CHAPA GENERICA', 106.22, '18/02/2026', 'ATIVO');
INSERT INTO PRODUTO (PRODUTOID, CATEGORIAPRODUTOID , DS_PRODUTO, OBS_PRODUTO,
VL_VENDA_PRODUTO, DT_CADASTRO_PRODUTO, STATUS_PRODUTO) VALUES (2, 1, 'FOLHA
METALICA', 'FOLHA GENERICA', 10.88, '18/02/2026', 'ATIVO');
INSERT INTO PRODUTO (PRODUTOID, CATEGORIAPRODUTOID , DS_PRODUTO, OBS_PRODUTO,
VL_VENDA_PRODUTO, DT_CADASTRO_PRODUTO, STATUS_PRODUTO) VALUES (3, 3, 'CHAPA
DOURADA', 'CHAPA ESPECIFICA', 158.88, '18/02/2026', 'ATIVO');
INSERT INTO PRODUTO (PRODUTOID, CATEGORIAPRODUTOID , DS_PRODUTO, OBS_PRODUTO,
VL_VENDA_PRODUTO, DT_CADASTRO_PRODUTO, STATUS_PRODUTO) VALUES (4, 4, 'FOLHA
DIAMANTE', 'FOLHA UNICA', 665.33, '18/02/2026', 'ATIVO');

INSERT INTO ORCAMENTO (ORCAMENTOID, CLIENTEID, DT_ORCAMENTO,
DT_VALIDADE_ORCAMENTO, VL_TOTAL_ORCAMENTO) VALUES (1, 1, '18/02/2026', '19/02/2026',
10700.00);
INSERT INTO ORCAMENTO (ORCAMENTOID, CLIENTEID, DT_ORCAMENTO,
DT_VALIDADE_ORCAMENTO, VL_TOTAL_ORCAMENTO) VALUES (2, 3, '17/02/2026', '19/02/2026',
2700.00);
INSERT INTO ORCAMENTO (ORCAMENTOID, CLIENTEID, DT_ORCAMENTO,
DT_VALIDADE_ORCAMENTO, VL_TOTAL_ORCAMENTO) VALUES (3, 4, '18/02/2026', '19/02/2026',
1200.00);
INSERT INTO ORCAMENTO (ORCAMENTOID, CLIENTEID, DT_ORCAMENTO,
DT_VALIDADE_ORCAMENTO, VL_TOTAL_ORCAMENTO) VALUES (4, 2, '17/02/2026', '19/02/2026',
8000.00);

INSERT INTO ORCAMENTO_ITEM (ORCAMENTOITEMID, ORCAMENTOID, PRODUTOID, QT_PRODUTO,
VL_UNITARIO, VL_TOTAL) VALUES (1, 1, 1, 10, 100.00, 1000.00);
INSERT INTO ORCAMENTO_ITEM (ORCAMENTOITEMID, ORCAMENTOID, PRODUTOID, QT_PRODUTO,
VL_UNITARIO, VL_TOTAL) VALUES (2, 1, 2, 20, 10.00, 200.00);
INSERT INTO ORCAMENTO_ITEM (ORCAMENTOITEMID, ORCAMENTOID, PRODUTOID, QT_PRODUTO,
VL_UNITARIO, VL_TOTAL) VALUES (3, 1, 4, 30, 500.00, 1500.00);
INSERT INTO ORCAMENTO_ITEM (ORCAMENTOITEMID, ORCAMENTOID, PRODUTOID, QT_PRODUTO,
VL_UNITARIO, VL_TOTAL) VALUES (4, 1, 3, 40, 200.00, 8000.00);

INSERT INTO ORCAMENTO_ITEM (ORCAMENTOITEMID, ORCAMENTOID, PRODUTOID, QT_PRODUTO,
VL_UNITARIO, VL_TOTAL) VALUES (5, 2, 1, 10, 100.00, 1000.00);
INSERT INTO ORCAMENTO_ITEM (ORCAMENTOITEMID, ORCAMENTOID, PRODUTOID, QT_PRODUTO,
VL_UNITARIO, VL_TOTAL) VALUES (6, 2, 2, 20, 10.00, 200.00);
INSERT INTO ORCAMENTO_ITEM (ORCAMENTOITEMID, ORCAMENTOID, PRODUTOID, QT_PRODUTO,
VL_UNITARIO, VL_TOTAL) VALUES (7, 2, 4, 30, 500.00, 1500.00);
INSERT INTO ORCAMENTO_ITEM (ORCAMENTOITEMID, ORCAMENTOID, PRODUTOID, QT_PRODUTO,
VL_UNITARIO, VL_TOTAL) VALUES (8, 3, 1, 10, 100.00, 1000.00);
INSERT INTO ORCAMENTO_ITEM (ORCAMENTOITEMID, ORCAMENTOID, PRODUTOID, QT_PRODUTO,
VL_UNITARIO, VL_TOTAL) VALUES (9, 3, 2, 20, 10.00, 200.00);
INSERT INTO ORCAMENTO_ITEM (ORCAMENTOITEMID, ORCAMENTOID, PRODUTOID, QT_PRODUTO,
VL_UNITARIO, VL_TOTAL) VALUES (10, 4, 3, 40, 200.00, 8000.00);