CREATE TABLE CATEGORIA_PRODUTO (
CATEGORIAPRODUTOID 		INTEGER NOT NULL,
DS_CATEGORIA_PRODUTO 	VARCHAR(50) NOT NULL,
PRIMARY KEY(CATEGORIAPRODUTOID));

CREATE TABLE CLIENTE(
CLIENTEID 			INTEGER NOT NULL,
TIPO_CLIENTE 		CHAR(1) NOT NULL,
CPF_CNPJ_CLIENTE 	VARCHAR(18) NOT NULL,
NOME_CLIENTE 		VARCHAR(100) NOT NULL,
PRIMARY KEY(CLIENTEID));

CREATE TABLE PRODUTO (
PRODUTOID 			INTEGER NOT NULL,
CATEGORIAPRODUTOID 	INTEGER NOT NULL,
DS_PRODUTO 			VARCHAR(50) NOT NULL,
OBS_PRODUTO 		VARCHAR(300) NULL,
VL_VENDA_PRODUTO 	NUMERIC(15,2) NOT NULL,
DT_CADASTRO_PRODUTO TIMESTAMP NOT NULL,
STATUS_PRODUTO 		VARCHAR(10) NOT NULL,
PRIMARY KEY(PRODUTOID),
FOREIGN KEY (CATEGORIAPRODUTOID) REFERENCES
CATEGORIA_PRODUTO (CATEGORIAPRODUTOID));

CREATE TABLE ORCAMENTO(
ORCAMENTOID 			INTEGER NOT NULL,
CLIENTEID 				INTEGER NOT NULL,
DT_ORCAMENTO 			TIMESTAMP NOT NULL,
DT_VALIDADE_ORCAMENTO 	TIMESTAMP NOT NULL,
VL_TOTAL_ORCAMENTO 		NUMERIC(15,2) NOT NULL,
PRIMARY KEY(ORCAMENTOID),
FOREIGN KEY(CLIENTEID) REFERENCES CLIENTE(CLIENTEID));

CREATE TABLE ORCAMENTO_ITEM(
ORCAMENTOITEMID 	INTEGER NOT NULL,
ORCAMENTOID 		INTEGER NOT NULL,
PRODUTOID 			INTEGER NOT NULL,
QT_PRODUTO 			NUMERIC(15,2) NOT NULL,
VL_UNITARIO 		NUMERIC(15,2) NOT NULL,
VL_TOTAL 			NUMERIC(15,2) NOT NULL,
PRIMARY KEY(ORCAMENTOITEMID),
FOREIGN KEY(ORCAMENTOID) REFERENCES ORCAMENTO
(ORCAMENTOID),
FOREIGN KEY(PRODUTOID) REFERENCES PRODUTO(PRODUTOID));

CREATE TABLE USUARIOS(
ID SERIAL 		PRIMARY KEY,
USUARIO 		VARCHAR(30),
NOME_COMPLETO 	VARCHAR(60),
SENHA 			VARCHAR(50));